(ert-deftest load-not-block ()
  (find-file "test/noblock.fth")
  (should (eq major-mode 'forth-mode))
  (should-not (and (boundp 'forth-block-mode) forth-block-mode))
  (kill-buffer))

(ert-deftest load-block-with-newlines ()
  (find-file "test/block2.fth")
  (should (eq major-mode 'forth-mode))
  (should (and (boundp 'forth-block-mode) forth-block-mode))
  (kill-buffer))

(ert-deftest load-block-without-newlines ()
  (find-file "test/block1.fth")
  (should (eq major-mode 'forth-mode))
  (should (and (boundp 'forth-block-mode) forth-block-mode))
  (kill-buffer))

(defmacro forth-with-temp-buffer (contents &rest body)
  (declare (indent 1) (debug t))
  `(with-temp-buffer
     (insert ,contents)
     (forth-mode)
     ,@body))

(defun forth-assert-face (content pos face)
  (forth-with-temp-buffer content
    (font-lock-fontify-buffer)
    (should (eq face (get-text-property pos 'face)))))

(ert-deftest forth-paren-comment-font-lock ()
  (forth-assert-face "( )" 1 font-lock-comment-delimiter-face)
  (forth-assert-face ".( )" 1 font-lock-comment-face)
  (forth-assert-face "( )" 3 font-lock-comment-delimiter-face)
  (forth-assert-face " ( )" 2 font-lock-comment-delimiter-face)
  (forth-assert-face "\t( )" 2 font-lock-comment-delimiter-face)
  (forth-assert-face "(\t)" 1 font-lock-comment-delimiter-face)
  (forth-assert-face "(foo) " 3 nil)
  (forth-assert-face "(foo)" 3 nil)
  (forth-assert-face "() " 2 nil)
  (forth-assert-face "( foo) " 3 font-lock-comment-face)
  (forth-assert-face "( a b --
                        x y )" 1 font-lock-comment-delimiter-face))

(ert-deftest forth-backslash-comment-font-lock ()
  (forth-assert-face "\\" 1 nil)
  (forth-assert-face "\\ " 1 font-lock-comment-delimiter-face)
  (forth-assert-face " \\" 2 nil)
  (forth-assert-face "\t\\ " 2 font-lock-comment-delimiter-face)
  (forth-assert-face " \\\t" 2 font-lock-comment-delimiter-face)
  (forth-assert-face " \\\n" 2 font-lock-comment-delimiter-face)
  (forth-assert-face "a\\b" 2 nil)
  (forth-assert-face "a\\b " 2 nil))

(ert-deftest forth-brace-colon-font-lock ()
  (forth-assert-face "{: :}" 1 font-lock-comment-face)
  (forth-assert-face "{: :}" 5 font-lock-comment-face)
  (forth-assert-face "{: a b :}" 4 font-lock-comment-face)
  (forth-assert-face "{::}" 1 nil)
  (forth-assert-face "{: a b --
                         x y :}" 1 font-lock-comment-face)
  (forth-assert-face "t{ 2 1+ -> 3 }t" 2 nil))

(ert-deftest forth-string-font-lock ()
  (forth-assert-face "s\" ab\"" 1 nil)
  (forth-assert-face "s\" ab\"" 2 font-lock-string-face)
  (forth-assert-face "abort\" ab\"" 6 font-lock-string-face)
  (forth-assert-face ".\" ab\"" 2 font-lock-string-face)
  (forth-assert-face "c\" ab\"" 2 font-lock-string-face)
  (forth-assert-face "[char] \" of" 10 nil)
  (forth-assert-face "frob\" ab\" " 6 nil)
  (forth-assert-face "s\\\" ab\"" 1 nil)
  (forth-assert-face "s\\\" ab\"" 3 font-lock-string-face)
  (forth-assert-face "s\\\" ab\"" 6 font-lock-string-face)
  (forth-assert-face "s\\\" a\\\"c\"" 7 font-lock-string-face)
  (forth-assert-face "s\\\" a\\\"c\" x" 10 nil))

(ert-deftest forth-parsing-words-font-lock ()
  (forth-assert-face "postpone ( x " 11 nil)
  (forth-assert-face "' s\" x " 6 nil))
