language: emacs-lisp
sudo: required
env:
  - EMACS=emacs23
  - EMACS=emacs24
  - EMACS=emacs-snapshot
install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo apt-get update -y
  - sudo apt-get install emacs23 emacs24 emacs-snapshot pforth
script: make EMACS=$EMACS
notifications:
  email: lars@nocrew.org
